#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'
juju-log "starting quasardb XTP daemon"
service qdbd start
juju-log "starting quasardb XTP web bridge"
service qdb_http start