#!/usr/bin/env python3

import amulet
import requests
import unittest


class TestDeployment(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.deployment = amulet.Deployment()

        cls.deployment.add('quasardb-xtp')
        cls.deployment.expose('quasardb-xtp')

        try:
            cls.deployment.setup(timeout=900)
            cls.deployment.sentry.wait()
        except amulet.helpers.TimeoutError:
            amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
        except:
            raise
        cls.unit = cls.deployment.sentry.unit['quasardb-xtp/0']

    def test_case(self):
        self.assertTrue(self.deployment)

        addr = self.unit.info['public-address']

        # if we connect to port 2836, it should work
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            s.connect(addr, 2836)
        except e:
            amulet.raise_status(amulet.FAIL, msg='Unable to connect to ' + addr + ':2836 - ' + str(e))

        # we should be able to access the console
        page = requests.get('http://' + addr + ':8080/console')
        page.raise_for_status()

if __name__ == '__main__':
    unittest.main()
